name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: Publish to AWS S3
      uses: opspresso/action-s3-sync@master
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-west-2"
          FROM_PATH: "./build"
          DEST_PATH: "s3://lmeikle-maverick/"
          OPTIONS: "--acl public-read"
    - name: Run Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        urls: 'http://lmeikle-maverick.s3-website.eu-west-2.amazonaws.com'
